version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports: 
      - 9092:9092
    environment: 
      KAFKA_ADVERTISED_HOST_NAME : localhost
      KAFKA_ZOOKEEPER_CONNECT : zookeeper
    volumes: 
      - kafka-data:/kafka
  redis:
    image: redis
    container_name: redis
    ports: 
      - 6379:6379
    volumes: 
      - redis-data:/data
  web:
    image: kvishe/assignment-demo
    container_name: web
    ports:
      - 8080:8080
volumes:
  kafka-data:
    driver: local
  redis-data:
    driver: local        